package app.domain.models.enums;

public enum OperationType {

    // ACCOUNTS
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_BLOCKED,
    ACCOUNT_CANCELLED,

    // LOANS
    LOAN_CREATED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_DISBURSED,
    LOAN_STATUS_CHANGED,

    // TRANSFERS
    TRANSFER_CREATED,
    TRANSFER_APPROVED,
    TRANSFER_REJECTED,
    TRANSFER_EXECUTED,
    TRANSFER_EXPIRED,
    TRANSFER_STATUS_CHANGED,

    // CUSTOMERS
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,

    // USERS
    USER_CREATED,
    USER_UPDATED,
    USER_BLOCKED,

    // LOGS / AUDIT
    OPERATION_LOG_CREATED
}
