package app.domain.models.enums;

public enum OperationType {

    // ACCOUNTS
    ACCOUNT_CREATED,

    // LOANS
    LOAN_CREATED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_DISBURSED,

    // TRANSFERS
    TRANSFER_CREATED,
    TRANSFER_APPROVED,
    TRANSFER_REJECTED,
    TRANSFER_EXECUTED,
    TRANSFER_EXPIRED,

    // CUSTOMERS
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,

    // USERS
    USER_CREATED,
    USER_UPDATED,
    USER_BLOCKED,
}
