package app.domain.models.enums;

public enum RoleType {
    BUSINESS_CUSTOMER,
    INDIVIDUAL_CUSTOMER,
    TELLER_EMPLOYEE,
    COMMERCIAL_EMPLOYEE,
    COMPANY_OPERATOR,
    COMPANY_SUPERVISOR,
    INTERNAL_ANALYST,
}
