spring.application.name=bank
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bank?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Migattenogokui12+
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/bank

#D. Qué debes cambiar de ese ejemplo

#Cambia según tu PC:

#root por tu usuario de MySQL
#pass por tu contraseña real
#bank por el nombre de tu base si quieres otro

#Ejemplo:

#spring.datasource.username=root
#spring.datasource.password=123456


#Este es el que se va a usar para la autenticación, esto para lo ultimo
#bearer Token